//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Envios
    {
        public int IdEnvio { get; set; }
        public int IdVenta { get; set; }
        public string Direccion { get; set; }
        public int Items { get; set; }
        public string Recibio { get; set; }
        public System.DateTime FechaEntrega { get; set; }
        public System.DateTime FechaCreación { get; set; }
    
        public virtual Ventas Ventas { get; set; }
    }
}
